package org.liftakids.entity.enm;

public enum NotificationType {

    // Institution Related
    INSTITUTION_REGISTRATION,
    INSTITUTION_APPROVED,
    INSTITUTION_REJECTED,
    INSTITUTION_SUSPENDED,
    INSTITUTION_PROFILE_UPDATE,

    // General
    SECURITY_ALERT,
    INFO,
    WARNING,
    ALERT,
    SUCCESS,
    // System/Admin
    ADMIN_ALERT,
    SYSTEM_ANNOUNCEMENT,
    // Donor Related
    DONOR_REGISTRATION,
    DONOR_PAYMENT_SUCCESS,
    DONOR_PAYMENT_FAILED,
    DONOR_SPONSORSHIP_STARTED,
    DONOR_SPONSORSHIP_ENDED,
    DONOR_PAYMENT_DUE,
    // Sponsor Related
    SPONSORSHIP_CREATED,
    SPONSORSHIP_UPDATED,
    SPONSORSHIP_COMPLETED,
    SPONSORSHIP_EXPIRED,
    PAYMENT_REMINDER,
    SPONSORSHIP_APPROVED,
    PAYMENT_RECEIVED,
    STUDENT_UPDATED,
    PAYMENT_CONFIRMED
}
